# Generated by Django 5.2.6 on 2025-09-30 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='template_fragment',
            field=models.CharField(blank=True, help_text='Eg: tools/fragments/json-formatter.html', max_length=250),
        ),
        migrations.AlterField(
            model_name='tool',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.category'),
        ),
    ]
