# Generated by Django 5.2.6 on 2025-09-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_category_tool_template_fragment_alter_tool_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='tool',
            name='js',
        ),
        migrations.AddField(
            model_name='tool',
            name='js_path',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='tool',
            name='template_fragment',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
